// Generated by CoffeeScript 1.10.0
(function() {
  var Firebase, title;

  Firebase = require("firebase");

  title = "aewens";

  exports.index = function(req, res) {
    return res.render("index", {
      title: title
    });
  };

  exports.partials = function(req, res) {
    return res.render("partials/" + req.params.name, {
      title: title
    });
  };

}).call(this);
